import json
import subprocess
import sys
from pathlib import Path


def test_miller_metal_slabs_match_ase_reference_counts():
    repo = Path(__file__).resolve().parents[1]
    script = repo / "tools" / "compare_adsorption_sites_against_reference_libs.py"
    subprocess.run([sys.executable, str(script)], check=True, cwd=repo)
    out = repo / "artifacts" / "autoresearch" / "physics_audit" / "site_reference_comparison.json"
    payload = json.loads(out.read_text(encoding="utf-8"))
    rows = payload.get("rows", [])
    assert rows, "No rows generated by site comparison audit."
    failures = []
    for row in rows:
        ref = row.get("ase_reference", {})
        if ref.get("status") != "ok":
            continue
        if not bool(ref.get("strict_mapped_counts_match")):
            failures.append(
                {
                    "slab": row.get("slab"),
                    "expected": ref.get("strict_mapped_counts_expected"),
                    "observed": ref.get("strict_mapped_counts_observed"),
                }
            )
    assert not failures, f"ASE strict mapped count mismatch: {failures}"

